package vn.dinosys.dinoad.data.database.table.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_INFO".
 */
public class UserInfo implements java.io.Serializable {

    private Long UserId;
    private String DisplayName;
    private Short CountryCode;
    private String PhoneNumber;
    private String Platform;

    public UserInfo() {
    }

    public UserInfo(Long UserId, String DisplayName, Short CountryCode, String PhoneNumber, String Platform) {
        this.UserId = UserId;
        this.DisplayName = DisplayName;
        this.CountryCode = CountryCode;
        this.PhoneNumber = PhoneNumber;
        this.Platform = Platform;
    }

    public Long getUserId() {
        return UserId;
    }

    public void setUserId(Long UserId) {
        this.UserId = UserId;
    }

    public String getDisplayName() {
        return DisplayName;
    }

    public void setDisplayName(String DisplayName) {
        this.DisplayName = DisplayName;
    }

    public Short getCountryCode() {
        return CountryCode;
    }

    public void setCountryCode(Short CountryCode) {
        this.CountryCode = CountryCode;
    }

    public String getPhoneNumber() {
        return PhoneNumber;
    }

    public void setPhoneNumber(String PhoneNumber) {
        this.PhoneNumber = PhoneNumber;
    }

    public String getPlatform() {
        return Platform;
    }

    public void setPlatform(String Platform) {
        this.Platform = Platform;
    }

}
