package vn.dinosys.dinoad.data.database.table.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import vn.dinosys.dinoad.data.database.table.dao.UserInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFO".
*/
public class UserInfoDao extends AbstractDao<UserInfo, Void> {

    public static final String TABLENAME = "USER_INFO";

    /**
     * Properties of entity UserInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property UserId = new Property(0, Long.class, "UserId", false, "USER_ID");
        public final static Property DisplayName = new Property(1, String.class, "DisplayName", false, "DISPLAY_NAME");
        public final static Property CountryCode = new Property(2, Short.class, "CountryCode", false, "COUNTRY_CODE");
        public final static Property PhoneNumber = new Property(3, String.class, "PhoneNumber", false, "PHONE_NUMBER");
        public final static Property Platform = new Property(4, String.class, "Platform", false, "PLATFORM");
    };


    public UserInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFO\" (" + //
                "\"USER_ID\" INTEGER," + // 0: UserId
                "\"DISPLAY_NAME\" TEXT," + // 1: DisplayName
                "\"COUNTRY_CODE\" INTEGER," + // 2: CountryCode
                "\"PHONE_NUMBER\" TEXT," + // 3: PhoneNumber
                "\"PLATFORM\" TEXT);"); // 4: Platform
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        Long UserId = entity.getUserId();
        if (UserId != null) {
            stmt.bindLong(1, UserId);
        }
 
        String DisplayName = entity.getDisplayName();
        if (DisplayName != null) {
            stmt.bindString(2, DisplayName);
        }
 
        Short CountryCode = entity.getCountryCode();
        if (CountryCode != null) {
            stmt.bindLong(3, CountryCode);
        }
 
        String PhoneNumber = entity.getPhoneNumber();
        if (PhoneNumber != null) {
            stmt.bindString(4, PhoneNumber);
        }
 
        String Platform = entity.getPlatform();
        if (Platform != null) {
            stmt.bindString(5, Platform);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public UserInfo readEntity(Cursor cursor, int offset) {
        UserInfo entity = new UserInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // UserId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // DisplayName
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2), // CountryCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // PhoneNumber
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // Platform
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserInfo entity, int offset) {
        entity.setUserId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDisplayName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCountryCode(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2));
        entity.setPhoneNumber(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPlatform(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(UserInfo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(UserInfo entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
